#pragma once
// clang-format off
// Generated by tools/travel_towns.py --emit-cpp. Do not hand-edit.
//
// Faction-tagged outdoor muster points, for starting a travel party at the closest
// friendly town to its destination rather than at one of four hand-picked capitals.
//
// Coordinates: game_graveyard_zone -> WorldSafeLocs.dbc. A graveyard is an outdoor,
// pathable spot beside a settlement, which is what a muster needs.
//
// team follows kMusters' convention: 2 = Alliance, 4 = Horde, 0 = neither. It is the
// zone's own AreaTable team where the zone has one, and for CONTESTED zones the modal
// side of the creature spawns within 300 yd -- because the zone team cannot separate
// Southshore from Tarren Mill, and game_graveyard_zone.faction answers a different
// question (who the graveyard serves, not whose town it is; Lakeshire's reads Horde
// because it catches Duskwood corpses).
//
// team 0 is NOT usable as a friendly muster without a decision. Most team-0 rows are
// wilderness graveyards, not towns at all (Felwood, Silithus, Moonglade); a few are
// real neutral ports (Booty Bay, Gadgetzan, Everlook) that either side could use.
struct TravelTown { uint32 team; uint32 map; float x, y, z; uint32 zone; char const* name; };

static TravelTown const kTravelTowns[] = {
    { 0, 0,    -6289.91f,    -3493.11f,    251.48f,     3, "Badlands, Graveyard NE " },  // Badlands
    { 0, 0,    -9004.55f,     3465.82f,     72.01f,  5561, "Balor" },  // Balor
    { 0, 0,   -10846.60f,    -2949.49f,     13.23f,     4, "Blasted Lands, Dreadmaul Hold" },  // Blasted Lands
    { 0, 0,   -11110.40f,    -1833.24f,     71.86f,    41, "Deadwind Pass, Morgan's Plot" },  // Deadwind Pass
    { 0, 0,   -10606.80f,      294.05f,     31.80f,    10, "Duskwood, Ravenhill" },  // Duskwood
    { 0, 0,     2647.55f,    -4014.39f,    105.94f,   139, "Eastern Plaguelands, Blackwood Lake" },  // Eastern Plaguelands
    { 0, 0,     1392.00f,    -3701.00f,     77.00f,   139, "Eastern Plaguelands, Darrowshire" },  // Eastern Plaguelands
    { 0, 0,     1978.47f,    -3655.89f,    119.79f,   139, "Eastern Plaguelands, Graveyard CG Tower" },  // Eastern Plaguelands
    { 0, 0,     2116.79f,    -5287.34f,     81.13f,   139, "Eastern Plaguelands, Light's Hope Chapel" },  // Eastern Plaguelands
    { 0, 0,    -1765.49f,     1607.01f,     58.16f,  5179, "Gilneas" },  // Gilneas
    { 0, 0,    -3588.13f,    -4628.86f,    188.86f,  5602, "Grim Reaches, Grim Batol Memorial" },  // Grim Reaches
    { 0, 0,   -11111.50f,    -1832.20f,     71.80f,  5086, "Karazhan Crypt, Morgan's Plot" },  // Karazhan Crypt
    { 0, 0,   -11505.10f,     3509.70f,     66.10f,   409, "Lapidis Isle" },  // Lapidis Isle
    { 0, 0,    -6690.38f,      -38.20f,    157.23f,  5581, "Northwind, Horde" },  // Northwind
    { 0, 0,    -6450.61f,    -1113.51f,    308.02f,    51, "Searing Gorge, Thorium Point" },  // Searing Gorge
    { 0, 0,   -14285.00f,      288.45f,     32.33f,    33, "Stranglethorn Vale, Booty Bay" },  // Stranglethorn Vale
    { 0, 0,     -291.00f,    -4374.00f,    107.00f,    47, "The Hinterlands, The Overlook Cliffs" },  // The Hinterlands
    { 0, 0,     1236.89f,    -2411.99f,     60.68f,    28, "Western Plaguelands, Caer Darrow" },  // Western Plaguelands
    { 0, 0,    -3347.72f,     -856.71f,      1.06f,    11, "Wetlands, Baradin Bay" },  // Wetlands
    { 0, 0,    -3289.12f,    -2435.99f,     18.60f,    11, "Wetlands, Crossroads" },  // Wetlands
    { 0, 1,     2421.72f,    -2953.62f,    123.47f,   331, "Ashenvale, Kargathia" },  // Ashenvale
    { 0, 1,     4788.78f,    -6845.00f,     89.79f,    16, "Azshara, Legash Encampment" },  // Azshara
    { 0, 1,     2942.76f,    -6037.13f,      5.17f,    16, "Azshara, Southridge Beach" },  // Azshara
    { 0, 1,    -8453.40f,    -4690.70f,   -202.90f,  1941, "Caverns of Time" },  // Caverns of Time
    { 0, 1,    -3127.69f,    -3046.94f,     33.83f,    15, "Dustwallow Marsh, Brackenwall Village" },  // Dustwallow Marsh
    { 0, 1,     5935.47f,    -1217.75f,    383.20f,   361, "Felwood, Irontree Woods" },  // Felwood
    { 0, 1,     3806.54f,    -1600.29f,    218.83f,   361, "Felwood, Morlos'Aran" },  // Felwood
    { 0, 1,    -4590.41f,     1632.08f,     93.97f,   357, "Feralas, Dire Maul" },  // Feralas
    { 0, 1,     4800.63f,    -1573.66f,   1308.73f,   616, "Hyjal" },  // Hyjal
    { 0, 1,     5509.87f,    -3845.95f,   1611.58f,   616, "Hyjal, Nordanaar" },  // Hyjal
    { 0, 1,     7426.00f,    -2809.00f,    464.00f,   493, "Moonglade" },  // Moonglade
    { 0, 1,    -6831.32f,      891.44f,     33.87f,  1377, "Silithus, Cenarion Hold" },  // Silithus
    { 0, 1,    -7991.57f,     1557.80f,      4.97f,  1377, "Silithus, Scarab Wall (AQ Only)" },  // Silithus
    { 0, 1,    -6432.26f,     -278.29f,      3.79f,  1377, "Silithus, Valor's Rest" },  // Silithus
    { 0, 1,      898.26f,      434.53f,     65.73f,   406, "Stonetalon Mountains, Webwinder Path" },  // Stonetalon Mountains
    { 0, 1,    -7190.95f,    -3944.65f,      9.23f,   440, "Tanaris, Gadgetzan" },  // Tanaris
    { 0, 1,    -5530.28f,    -3459.28f,    -45.74f,   400, "Thousand Needles, Shimmering Flats" },  // Thousand Needles
    { 0, 1,    -7205.56f,    -2436.67f,   -218.16f,   490, "Un'Goro Crater, The Marshlands" },  // Un'Goro Crater
    { 0, 1,     6875.76f,    -4661.54f,    701.09f,   618, "Winterspring, Everlook" },  // Winterspring
    { 2, 0,     4287.19f,    -2859.97f,      5.30f,  2040, "Alah'Thalas, Alliance Graveyard" },  // Alah'Thalas
    { 2, 0,    -1472.29f,    -2617.96f,     49.28f,    45, "Arathi Highlands" },  // Arathi Highlands
    { 2, 0,    -6164.23f,      336.32f,    399.79f,     1, "Dun Morogh, Anvilmar" },  // Dun Morogh
    { 2, 0,    -5165.52f,     -874.66f,    507.18f,     1, "Dun Morogh, Gates of Ironforge" },  // Dun Morogh
    { 2, 0,    -5680.04f,     -518.92f,    396.27f,     1, "Dun Morogh, Kharanos" },  // Dun Morogh
    { 2, 0,   -10774.30f,    -1189.67f,     33.15f,    10, "Duskwood, Darkshire" },  // Duskwood
    { 2, 0,    -9552.46f,    -1374.05f,     51.23f,    12, "Elwynn Forest, Eastvale Logging Camp" },  // Elwynn Forest
    { 2, 0,    -9339.46f,      171.41f,     61.56f,    12, "Elwynn Forest, Goldshire" },  // Elwynn Forest
    { 2, 0,    -8935.33f,     -188.65f,     80.42f,    12, "Elwynn Forest, Northshire" },  // Elwynn Forest
    { 2, 0,    -9151.98f,      410.94f,     92.70f,    12, "Elwynn Forest, Stormwind" },  // Elwynn Forest
    { 2, 0,    -5046.60f,    -4807.58f,    216.20f,  5602, "Grim Reaches, Dun Kithas" },  // Grim Reaches
    { 2, 0,     -732.80f,     -592.50f,     22.66f,   267, "Hillsbrad Foothills, Southshore" },  // Hillsbrad Foothills
    { 2, 0,    -5351.23f,    -2881.58f,    340.94f,    38, "Loch Modan, Thelsamar" },  // Loch Modan
    { 2, 0,    -7353.24f,      618.17f,     62.17f,  5581, "Northwind, Alliance" },  // Northwind
    { 2, 0,    -9403.25f,    -2037.69f,     58.37f,    44, "Redridge Mountains, Lakeshire" },  // Redridge Mountains
    { 2, 0,   -11542.60f,     -228.64f,     27.84f,    33, "Stranglethorn Vale, Northern Stranglethorn" },  // Stranglethorn Vale
    { 2, 0,     3128.28f,    -2522.96f,    113.56f,  5225, "Thalassian Highlands" },  // Thalassian Highlands
    { 2, 0,      323.51f,    -2227.20f,    137.62f,    47, "The Hinterlands, Aerie Peak" },  // The Hinterlands
    { 2, 0,      908.32f,    -1520.29f,     55.04f,    28, "Western Plaguelands, Chillwind Camp" },  // Western Plaguelands
    { 2, 0,   -10546.90f,     1197.24f,     31.73f,    40, "Westfall, Sentinel Hill" },  // Westfall
    { 2, 1,     2633.41f,     -629.73f,    107.58f,   331, "Ashenvale, Astranaar" },  // Ashenvale
    { 2, 1,     2681.06f,    -4009.75f,    107.85f,    16, "Azshara, Talrendis Point" },  // Azshara
    { 2, 1,     6739.19f,      209.99f,     23.28f,   148, "Darkshore, Auberdine" },  // Darkshore
    { 2, 1,     4291.28f,       96.96f,     43.08f,   148, "Darkshore, Twilight Vale" },  // Darkshore
    { 2, 1,    -3525.71f,    -4315.46f,      7.00f,    15, "Dustwallow Marsh, Theramore Isle" },  // Dustwallow Marsh
    { 2, 1,    -4596.40f,     3229.43f,      8.99f,   357, "Feralas, Feathermoon Stronghold" },  // Feralas
    { 2, 1,    10384.80f,      811.53f,   1317.54f,   141, "Teldrassil, Aldrassil" },  // Teldrassil
    { 2, 1,    10054.30f,     2117.12f,   1329.63f,   141, "Teldrassil, Darnassus" },  // Teldrassil
    { 2, 1,     9701.25f,      945.62f,   1291.35f,   141, "Teldrassil, Dolanaar" },  // Teldrassil
    { 4, 0,    -6805.00f,    -2287.19f,    280.75f,     3, "Badlands, Kargath" },  // Badlands
    { 4, 0,    -7490.45f,    -2132.62f,    142.19f,    46, "Burning Steppes, Flame Crest" },  // Burning Steppes
    { 4, 0,      -18.68f,     -981.17f,     55.84f,   267, "Hillsbrad Foothills, Tarren Mill" },  // Hillsbrad Foothills
    { 4, 0,      516.19f,     1589.81f,    127.54f,   130, "Silverpine Forest, The Sepulcher" },  // Silverpine Forest
    { 4, 0,   -10567.80f,    -3377.20f,     22.25f,     8, "Swamp of Sorrows, Stonard" },  // Swamp of Sorrows
    { 4, 0,     2348.67f,      492.03f,     33.37f,    85, "Tirisfal Glades, Brill" },  // Tirisfal Glades
    { 4, 0,     1882.94f,     1629.11f,     94.42f,    85, "Tirisfal Glades, Deathknell" },  // Tirisfal Glades
    { 4, 0,     2604.52f,     -543.39f,     89.00f,    85, "Tirisfal Glades, Faol's Rest" },  // Tirisfal Glades
    { 4, 0,     1780.11f,      221.76f,     59.62f,    85, "Tirisfal Glades, Ruins of Lordaeron" },  // Tirisfal Glades
    { 4, 0,     1750.34f,     -669.79f,     44.57f,    28, "Western Plaguelands, Bulwark" },  // Western Plaguelands
    { 4, 1,     2947.03f,     2557.98f,    139.30f,  2041, "Amani'Alor" },  // Amani'Alor
    { 4, 1,     -124.92f,    -7550.25f,     40.70f,  5536, "Blackstone Island" },  // Blackstone Island
    { 4, 1,    -1443.49f,     1973.37f,     85.49f,   405, "Desolace, Ghost Walker Post" },  // Desolace
    { 4, 1,     1177.78f,    -4464.24f,     21.35f,    14, "Durotar, Northern Durotar" },  // Durotar
    { 4, 1,      233.46f,    -4793.73f,     10.19f,    14, "Durotar, Razor Hill" },  // Durotar
    { 4, 1,     -778.00f,    -4985.00f,     19.00f,    14, "Durotar, Sen'jin Village" },  // Durotar
    { 4, 1,     -634.64f,    -4296.03f,     40.53f,    14, "Durotar, Valley of Trials" },  // Durotar
    { 4, 1,    -4439.97f,      370.15f,     51.36f,   357, "Feralas, Camp Mojache" },  // Feralas
    { 4, 1,    -4631.85f,    -3133.48f,     34.92f,  4010, "Mudsprocket" },  // Mudsprocket
    { 4, 1,    -2175.19f,     -342.03f,     -5.51f,   215, "Mulgore, Bloodhoof Village" },  // Mulgore
    { 4, 1,    -2944.56f,     -153.21f,     65.79f,   215, "Mulgore, Red Cloud Mesa" },  // Mulgore
    { 4, 1,     -981.92f,      -74.65f,     20.13f,   215, "Mulgore, Thunder Bluff" },  // Mulgore
    { 4, 1,    -2517.75f,    -1972.64f,     91.78f,    17, "The Barrens, Camp Taurajo" },  // The Barrens
    { 4, 1,    -1081.40f,    -3478.68f,     63.61f,    17, "The Barrens, Ratchet" },  // The Barrens
    { 4, 1,     -592.60f,    -2523.49f,     91.79f,    17, "The Barrens, The Crossroads" },  // The Barrens
    { 4, 1,    -4656.00f,    -1765.00f,    -41.00f,   400, "Thousand Needles, The Great Lift" },  // Thousand Needles
};

// 94 musters: 39 contested, 29 Alliance, 26 Horde
