#pragma once
// clang-format off
// Generated by tools/dungeon_entrances.py --emit-cpp. Do not hand-edit.
// One row per instance, keyed on AreaTrigger.dbc trigger id (NOT destination map id:
// Grim Batol and Wailing Caverns both report map 43).
//
// reqLevel is the game's own hard gate from areatrigger_teleport. min/maxLevel is the
// recommended recruiting band, never below reqLevel. Rows with reqLevel > 60 are
// unreachable at this core's level cap and must be skipped by selection.
//
// map/x/y/z is the DOOR, on the outdoor map - what a party walks to. inMap/inX/inY/inZ/inO
// is where crossing that door puts a player, i.e. areatrigger_teleport's own target, and
// is what G5b teleports an arrived party to.
//
// isRaid comes from Map.dbc's instanceType (2 = raid). A party may still MARCH to a raid
// door - that is a real journey and the whole point of the registry - but 5 bots must not
// be teleported inside one, so entering is dungeons only.
struct TravelDest { uint32 trigger; uint32 map; float x, y, z;
                    uint8 minLevel, maxLevel, reqLevel; char const* name;
                    uint32 inMap; float inX, inY, inZ, inO; bool isRaid; };

static TravelDest const kTravelDests[] = {
    {  1632, 1,   -8799.19f,   -4115.16f,  -200.00f, 58, 60, 58, "Black Morass", 269,  -2002.50f,   6575.30f,  -154.90f, 5.70f, false },  // band = reqLevel..cap, no conventional range
    {   257, 1,    4252.37f,     756.97f,   -23.06f, 24, 32, 10, "Blackfathom Deeps",  48,   -150.23f,    106.59f,   -39.78f, 4.45f, false },
    {  1466, 0,   -7176.63f,    -937.67f,   170.21f, 52, 60, 40, "Blackrock Depths", 230,    456.93f,     34.09f,   -68.09f, 4.71f, false },
    {  1468, 0,   -7518.19f,   -1239.13f,   287.24f, 55, 60, 45, "Blackrock Spire", 229,     78.35f,   -226.84f,    49.77f, 4.71f, false },
    {  5004, 1,    1689.78f,   -1272.15f,   161.68f, 32, 60, 32, "Crescent Grove", 802,    579.13f,     90.70f,   276.11f, 3.40f, false },  // band = reqLevel..cap, no conventional range
    {    78, 0,  -11208.50f,    1685.34f,    25.76f, 17, 26, 10, "Deadmines",  36,    -14.57f,   -385.48f,    62.46f, 1.57f, false },
    {  3183, 1,   -3730.48f,     933.97f,   160.97f, 55, 60, 45, "Dire Maul", 429,     47.45f,   -153.66f,    -2.71f, 5.50f, false },  // 6 doors, canonical picked
    {  5017, 1,    4833.13f,   -1756.65f,  1158.04f, 60, 60, 60, "Emerald Sanctum", 807,   2762.25f,   2972.77f,    26.90f, 1.90f, true  },  // band = reqLevel..cap, no conventional range
    {  5014, 0,   -1096.81f,    2234.77f,   182.86f, 40, 60, 40, "Gilneas City", 815,  -1100.00f,   2237.75f,   182.86f, 2.60f, false },  // band = reqLevel..cap, no conventional range
    {   324, 0,   -5161.33f,     939.62f,   258.29f, 29, 38, 15, "Gnomeregan",  90,   -329.10f,     -3.21f,  -152.85f, 2.97f, false },  // 2 doors, canonical picked
    {  5337, 0,   -3696.12f,   -3359.85f,   267.14f, 61, 61, 61, "Grim Batol",  43,   -158.44f,    131.60f,   -74.26f, 5.85f, false },  // band = reqLevel..cap, no conventional range; OVER LEVEL CAP - skip
    {  5009, 0,   -8173.00f,   -3114.57f,   201.22f, 48, 60, 48, "Hateforge Quarry", 808,  -8173.90f,  -3120.60f,   199.80f, 4.70f, false },  // band = reqLevel..cap, no conventional range
    {  5008, 0,  -11068.30f,   -1811.69f,    53.00f, 55, 60, 55, "Karazhan Crypt", 800, -11068.10f,  -1806.40f,    52.70f, 1.50f, false },  // band = reqLevel..cap, no conventional range
    {  5018, 0,  -11110.50f,   -2004.25f,    49.33f, 60, 60, 60, "Lower Karazhan Halls", 532, -11104.30f,  -1999.42f,    49.89f, 0.60f, true  },  // band = reqLevel..cap, no conventional range
    {  3133, 1,   -1484.07f,    2617.57f,    75.71f, 46, 55, 30, "Maraudon", 349,   1016.83f,   -458.52f,   -43.47f, 6.28f, false },  // 2 doors, canonical picked
    {  3528, 0,   -7510.87f,   -1035.87f,   182.95f, 50, 60, 50, "Molten Core", 409,   1091.89f,   -466.99f,  -105.08f, 3.14f, true  },  // 2 doors, canonical picked; band = reqLevel..cap, no conventional range
    {  4055, 0,    3133.15f,   -3730.29f,   138.66f, 60, 60, 60, "Naxxramas", 533,   3005.87f,  -3435.01f,   293.88f, 0.00f, true  },  // band = reqLevel..cap, no conventional range
    {  2848, 1,   -4768.61f,   -3752.11f,    53.43f, 50, 60, 50, "Onyxia's Lair", 249,     30.89f,    -54.08f,    -5.03f, 4.71f, true  },  // band = reqLevel..cap, no conventional range
    {  2230, 1,    1818.40f,   -4427.26f,   -10.45f, 13, 18,  8, "Ragefire Chasm", 389,      0.80f,     -8.23f,   -15.53f, 4.71f, false },
    {   442, 1,   -4666.52f,   -2536.82f,    86.97f, 37, 46, 25, "Razorfen Downs", 129,   2593.68f,   1111.23f,    50.95f, 4.71f, false },
    {   244, 1,   -4456.70f,   -1655.99f,    86.11f, 29, 38, 15, "Razorfen Kraul",  47,   1942.27f,   1544.23f,    83.31f, 1.31f, false },
    {  4008, 1,   -8424.94f,    1508.65f,    32.01f, 60, 60, 60, "Ruins Of Ahn'Qiraj", 509,  -8436.53f,   1519.17f,    31.91f, 2.62f, true  },  // band = reqLevel..cap, no conventional range
    {   612, 0,    2877.98f,    -839.27f,   163.05f, 38, 44, 20, "Scarlet Monastery Armory", 189,   1608.10f,   -318.92f,    18.67f, 4.71f, false },
    {   610, 0,    2925.18f,    -820.54f,   161.63f, 40, 46, 20, "Scarlet Monastery Cathedral", 189,    853.18f,   1319.18f,    18.67f, 1.57f, false },
    {    45, 0,    2924.38f,    -798.43f,   161.61f, 34, 40, 20, "Scarlet Monastery Graveyard", 189,   1687.27f,   1050.09f,    18.68f, 1.57f, false },
    {   614, 0,    2859.73f,    -824.91f,   162.08f, 36, 42, 20, "Scarlet Monastery Library", 189,    253.67f,   -206.62f,    18.68f, 4.71f, false },
    {  2567, 0,    1282.05f,   -2548.73f,    85.40f, 58, 60, 45, "Scholomance", 289,    190.82f,    126.33f,   137.23f, 6.28f, false },
    {   145, 0,    -229.49f,    1576.35f,    78.89f, 22, 30, 10, "Shadowfang Keep",  33,   -228.19f,   2111.41f,    76.89f, 1.22f, false },
    {   101, 0,   -8761.85f,     848.56f,    87.81f, 24, 32, 15, "Stormwind Stockades",  34,     48.98f,      0.48f,   -16.39f, 6.28f, false },
    {   107, 0,   -8667.56f,     623.56f,    85.41f, 58, 60, 58, "Stormwind Vault",  35,     -0.91f,     40.57f,   -24.23f, 1.52f, false },  // 3 doors, canonical picked; band = reqLevel..cap, no conventional range
    {  2214, 0,    3237.46f,   -4060.60f,   112.01f, 58, 60, 45, "Stratholme", 329,   3590.87f,  -3643.22f,   138.49f, 5.50f, false },  // 3 doors, canonical picked
    {   446, 0,  -10162.70f,   -3998.65f,  -107.98f, 50, 60, 35, "Sunken Temple", 109,   -315.90f,    100.20f,  -131.85f, 3.14f, false },
    {  4010, 1,   -8230.40f,    2005.33f,   129.86f, 60, 60, 60, "Temple of Ahn'Qiraj", 531,  -8221.35f,   2014.34f,   129.07f, 0.87f, true  },  // band = reqLevel..cap, no conventional range
    {   286, 0,   -6053.73f,   -2954.63f,   213.69f, 41, 51, 30, "Uldaman",  70,   -228.86f,     46.10f,   -46.02f, 1.57f, false },  // 2 doors, canonical picked
    {   228, 1,    -753.60f,   -2212.78f,    21.54f, 17, 24, 10, "Wailing Caverns",  43,   -158.44f,    131.60f,   -74.26f, 5.85f, false },
    {   924, 1,   -6773.49f,   -2889.77f,    15.11f, 44, 54, 35, "Zul'Farrak", 209,   1212.67f,    842.04f,     8.93f, 6.28f, false },
    {  3928, 0,  -11915.80f,   -1236.43f,    96.15f, 60, 60, 60, "Zul'Gurub", 309, -11916.60f,  -1243.52f,    92.53f, 4.71f, true  },  // band = reqLevel..cap, no conventional range
};

// 37 instances, all with a level floor from the game's own data.
// Over the level cap, skip in selection: Grim Batol (req 61)
